kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx-ns
  labels:
    name: nginx
spec:
  # The pod restart always if the container is terminated
  restartPolicy: Always
  #restartPolicy: OnFailure
  initContainers:
  - name: nginx-init
    image: docker/whalesay:latest
    command: [sh, -c]
    args: [echo "<pre>$(cowsay -b 'Hello Kubernetes')</pre>" > /data/index.html]
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - name: nginx
    image: nginx:1.21.6
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
  - name: data
    emptyDir: {}
