apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: php-ns
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30010
  selector:
    run: php-apache
